"""add_ml_features

Revision ID: 11e7eaaa4dbb
Revises: 6b138e8a4921
Create Date: 2026-04-21 15:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e7eaaa4dbb'
down_revision = '6b138e8a4921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('lead_time_dias', sa.Integer(), nullable=False))
    op.add_column('agendamentos', sa.Column('priority_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'priority_score')
    op.drop_column('agendamentos', 'lead_time_dias')
    # ### end Alembic commands ###