"""create agendamento_consulta

Revision ID: 6775678cfdec
Revises: b28d1c976bbf
Create Date: 2026-04-21 15:20:18.730406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6775678cfdec'
down_revision: Union[str, Sequence[str], None] = 'b28d1c976bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    op.drop_table('pacientes')
    op.drop_table('familias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familias',
    sa.Column('familia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('responsavel_nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('num_membros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_familia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('familia_id', name=op.f('familias_pkey'))
    )
    op.create_table('pacientes',
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('familia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_risco_saude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comorbidades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('paciente_id', name=op.f('pacientes_pkey'))
    )
    op.create_table('agendamentos',
    sa.Column('table_name,column_name,data_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_criada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_agendada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_realizada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('no_show', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('especialidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duracao_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_show_history', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agendamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_time_dias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.paciente_id'], name=op.f('agendamentos_paciente_id_fkey'))
    )
    # ### end Alembic commands ###
