"""add_ml_features_paciente_agendamento

Revision ID: 74fe5a0508c6
Revises: 11e7eaaa4dbb
Create Date: 2026-04-21 18:06:21.534281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74fe5a0508c6'
down_revision: Union[str, Sequence[str], None] = '11e7eaaa4dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_data_consulta'), table_name='agendamento_consulta')
    op.drop_index(op.f('idx_paciente_data'), table_name='agendamento_consulta')
    op.drop_table('agendamento_consulta')
    op.drop_table('paciente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('risco_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('paciente_pkey'))
    )
    op.create_table('agendamento_consulta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unidade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profissional_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('especialidade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_consulta', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hora', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('no_show', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('agendamento_consulta_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agendamento_consulta_pkey'))
    )
    op.create_index(op.f('idx_paciente_data'), 'agendamento_consulta', ['paciente_id', 'data_consulta'], unique=False)
    op.create_index(op.f('idx_data_consulta'), 'agendamento_consulta', ['data_consulta'], unique=False)
    # ### end Alembic commands ###
